autoload :BasicSet, 'fixtures/basic_set'
autoload :BasicSetMap, 'fixtures/basic_set_map'
autoload :ControllerConstants, 'fixtures/controller_constants'
autoload :DeeplyNestedSet, 'fixtures/deeply_nested_set'
autoload :DefaultSet, 'fixtures/default_set'
autoload :EchoApp, 'fixtures/echo_app'
autoload :LinearBasicSet, 'fixtures/linear_basic_set'
autoload :OptimizedBasicSet, 'fixtures/optimized_basic_set'
